plugins {
	id 'java'
	id 'application'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    implementation project(':Core')
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.google.guava:guava:33.0.0-jre'
    implementation 'com.networknt:json-schema-validator:1.5.8'
	implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-websocket:3.5.3'
	testImplementation 'org.mockito:mockito-core:5.18.0'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
	//testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


tasks.named('test') {
	useJUnitPlatform()
}
// Disable all Spring Boot application packaging tasks
tasks.named('bootJar') {
    enabled = false
}
tasks.named('jar') {
    enabled = true
    archiveBaseName.set("Checkers")
    archiveClassifier.set("")
    archiveVersion.set("")
}

task CheckersJar(type: Jar) {
    archiveBaseName = 'Checkers'
    
    // grab compiled classes
    from(sourceSets.main.output) {
        include 'checkers/model/**'
        include 'checkers/control/**'
    }
}

task UIJar(type: Jar) {
    archiveBaseName = 'CheckersUI'
    
    // grab compiled classes
    from(sourceSets.main.output) {
        include 'checkers/model/**'
        include 'checkers/ui/**'
    }
}

tasks.matching { it.name.startsWith("bootDist") || it.name.startsWith("bootStart") }.configureEach {
    enabled = false
}
